### ISSUE TITLE
`tha` doesn't trigger suggestions for Kannada equivalent ಥ, despite being in `phone` key in the data

### ISSUE THREAD

**Issue by arihantverma** [alar-dict/alar.ink#14]
[data yml file link](https://github.com/alar-dict/data)

```yaml
# line number starting 896721
- id: 78432
  head: ಥ
  entry: ಥ
  phone: tha
  origin: ""
  info: ""
  defs:
  - id: 194178
    entry: (gen. pronounced with the vowel 'ಅ') the thirty first letter of Kannaḍa alphabet and the seventeenth consonant.
    type: noun
  - id: 221995
    entry: a symbol for the number seven.
    type: noun
```

<img width="1035" alt="Image" src="https://github.com/user-attachments/assets/092333fa-9bc4-49f6-9c8e-f86f5ed0cf29" />

<img width="1435" alt="Image" src="https://github.com/user-attachments/assets/0159b670-275e-42c5-ac58-c396baab389e" />
